In [1]:
import tensorflow as tf 


In [2]:
a = tf.constant([2]) # source op 1

In [4]:
b = tf.constant([3]) # source op 2 

In [5]:
c = tf.add(a,b) ## op

In [6]:
session = tf.Session() # operations are run in Sessions.
res = session.run(c)
print(res)

[5]


In [7]:
session.close()
# or 

with tf.Session as session : 
    res = session.run(c)
    print(res)

AttributeError: __enter__

In [8]:
x = tf.constant([2]) # 1-D
y = tf.constant([1,2,3]) 
z = tf.constant([ [1,2,3],
                 [4,5,6]    
                ])

z1 = tf.constant([
    
])

In [9]:
sess = tf.Session()
yv = session.run(y)
print("y is  %s" %  yv)
session.run(z)

RuntimeError: Attempted to use a closed Session.

In [22]:
x1 = tf.constant([[2,3],[2,3]])

x2 = tf.constant([[1,1],[1,1]])

x = x1+x2 
y = x1 * x2
z = tf.matmul(x1,x2)
    
    

In [24]:
session =  tf.Session()
res = session.run(x)
print(res)
mulres = session.run(y)
matmulres = session.run(z)


[[3 4]
 [3 4]]


In [21]:
print(mulres)

[[2 3]
 [2 3]]


In [25]:
print(matmulres)

[[5 5]
 [5 5]]


In [26]:
for _ in range(3):
    print("Wth is this")

Wth is this
Wth is this
Wth is this


In [28]:
#Variables 

var1 = tf.Variable(0)

one = tf.constant(1)
newVal = one + var1
update = tf.assign(var1,newVal)


In [30]:
# initialize the variables 
init_op = tf.global_variables_initializer()

In [33]:
with tf.Session() as s : 
    s.run(init_op)
    print(s.run(var1))
    for _ in range(3):
        #s.run(newVal)
        print(s.run(update))

0
1
2
3


In [35]:
#Placeholders 

a = tf.placeholder(tf.int32)

b = a * 5

with tf.Session() as s : 
    res = s.run(b, feed_dict= {a : 51})
    print(res)


255


In [23]:
## Linear Regression
import numpy as np 
import tensorflow as tf 


In [24]:
xdata  = np.random.rand(100).astype(np.float32)
ydata = 3*xdata + 2 

## add some noise 

y_data = np.vectorize(lambda y: y + np.random.normal(loc=0.0, scale=0.1))(ydata)


In [55]:
c = tf.Variable(2.0)
d = tf.Variable(0.2)

In [56]:
y = c*xdata + d 

In [36]:
loss = tf.reduce_mean( tf.square(y-ydata) )

In [38]:
optimizer = tf.train.GradientDescentOptimizer(0.5)
train = optimizer.minimize(loss)

In [39]:
init = tf.initialize_all_variables()
sess  = tf.Session()
sess.run(init)

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [57]:
train_data = []
for step in range(50):
    evals = sess.run([train,a,b])[1:]
    #print(evals)
    if step % 5 == 0:
        print(step, evals)
        train_data.append(evals)

0 [2.999999, 2.0000005]
5 [2.999999, 2.0000005]
10 [2.999999, 2.0000005]
15 [2.999999, 2.0000005]
20 [2.999999, 2.0000005]
25 [2.999999, 2.0000005]
30 [2.999999, 2.0000005]
35 [2.999999, 2.0000005]
40 [2.999999, 2.0000005]
45 [2.999999, 2.0000005]
